services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: docs-hub-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - .env
    networks:
      - docs-hub-network


networks:
  docs-hub-network:
    driver: bridge